name: AutoOTP CI

on:
  push:
    branches: [ master , develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Generating keystores.jks
      run: |
        echo '${{ secrets.KEYSTOREB64 }}' | base64 --decode > keystore.jks 
        
    - name: Generating keystores.jks
      run: |
        echo '${{ secrets.KEYSB64 }}' | base64 --decode > keystore.properties 

    - name: Build with Gradle
      run: ./gradlew assembleRelease --stacktrace

    - name: Archive output apk
      uses: actions/upload-artifact@v2
      with:
        name: output-apk.zip
        path: app/build/outputs/apk/release/auto-otp-v*.apk
