name: AutoOTP CI

on:
  push:
    branches: [ master , develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generating keystores.jks
      run: base64 --decode ${{ secrets.KEYSTOREB64 }} > keystore.jks
    - name: Generating keystores.properties
      run: echo ${{ secrets.KEYS }} > keystore.properties
    - name: Build with Gradle
      run: ./gradlew assembleRelease --stacktrace
    - name: Archive output apk
      uses: actions/upload-artifact@v2
      with:
        name: output-apk
        path: app/build/outputs/apk/release/auto-otp-v*.apk
